### ISSUE TITLE
TODO - Project Organization: Write project README

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#2]
**Task:** Provide a project README

**Comment by callahantiff** [comment]
In progress! Closing issue.

**Comment by callahantiff** [comment]
**Reopening Issue:**   
- [ ] Needs some work and additional details on where to access finalized mapping files  
- [ ] Decide which versions of the mapping files to release

**Comment by callahantiff** [comment]
Extend description of how to run the following code:
- [ ] TF-IDF scoring  
- [ ] BERT Multilabel Classification pipeline

**Comment by callahantiff** [comment]
In progress and nearly complete. Closing this issue.
