### ISSUE TITLE
TODO - Project Organization: Create README for Mapping Directory

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#20]
**Task:** Add README docs to each of the clinical domain directories described below.

**Description:** Create a README to describe the formatting of each mapping file that will be added to this directory
- [x] `resources/mapping/conditions`  
- [x] `resources/mapping/measurements`  
- [x] `resources/mapping/medications`

**Comment by callahantiff** [comment]
- The input requirements for each type of these data can be found [here](https://github.com/callahantiff/OMOP2OBO/tree/master/resources/clinical_data)  

- Content on the mapping output files will be added to the wiki and updated according to issue #34
