### ISSUE TITLE
Project Meeting -- 05/28/2020 @ 14:30

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#22]
**Meeting Date:** May 28, 2020
**Topic:** Plan for incorporating MONDO into existing mappings
**Attendees:** @nicolevasilevsky 

**Proposed Agenda:**
- [x] Discuss how to best add MONDO mappings  
- [x] Understand whether to use MONDO as a replacement for DOID or include both ontologies  
- [x] Briefly chat about potential challenges to replacing DOID with MONDO in [PheKnowLator KR](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#release-v200-first-official-release)

**Comment by callahantiff** [comment]
**UPDATE:**  
MONDO subsumes DOID and incorporates annotations to other OBO ontologies that we have already mapped to in this project and in PheKnowLator. 

**TODO:**  
- [ ] Replace all DOID identifiers with MONDO identifiers using existing mappings in MONDO  
- [ ] If there are DOID concepts that we originally mapped to, but that we don't find a mapping for in MONDO we will follow-up with @nicolevasilevsky  
- [ ] Try to find a MONDO mapping for any DOID concepts we originally unable to map to  

**Timeframe:** I will shoot to have all resources updated by the end of next week

**Comment by callahantiff** [comment]
MONDO fully incorporated. Closing this issue. Thanks for all of your help @nicolevasilevsky!
