### ISSUE TITLE
Wiki: Re-organize wiki to support releases

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#31]
**Task:**  
- Overhaul (minor) existing organization of mapping content to enable better documentation and tracking of releases.   

**How:**  
-  [x] Add wiki tab for releases and add new entries for `v1.01` and `v2.0`  
- [x] Take current content from the `Conditions`, `Medications`, and `Measurements` sub-pages and split it by release into it's appropriate pages 

**New for `v2.0`:**  
- [x] Describe new ontologies added  
- [x] Incorporation of existing Loinc2HPO mappings  
- [x] Alignment and subsumption of Juan's `OHDSIananke` mapping method    
- [x] Better leveraging of OMOP concept hierarchies

**Comment by callahantiff** [comment]
Also would be helpful to add download links via Zenodo to frozen versions of the processed ontologies so people don't have to re-download and process them to use the code.

**Comment by callahantiff** [comment]
We have a workflow/Figure 1 now, woo!

![OMOP2OBO_Figures](https://user-images.githubusercontent.com/8030363/96070743-0778bd00-0e5e-11eb-982a-7bacd43a09aa.png)

**Comment by callahantiff** [comment]
@mgkahn - I think I made all of the requested changes. Does this look OK to you now (click on figure to enlarge)?

![OMOP2OBO_Figures](https://user-images.githubusercontent.com/8030363/96931469-99924e00-147a-11eb-9c19-fe5a95786772.png)

**Comment by callahantiff** [comment]
In Progress -- done enough to close this.
