### ISSUE TITLE
Add Jupyter Notebooks

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#32]
**Task:** Add Jupyter Notebooks for the following:  

- [x] Running the mapping pipeline -- take existing content from `main.py` and organize it in a similar fashion as done for PheKnowLator (we've had good feedback that this approach is user friendly)  

- [x] Performing coverage studies using Concept Prevalence data  

- [x] Aligning outside OMOP concepts to the current main mapping file and outputting useful information for next steps

**Comment by callahantiff** [comment]
- [x] Running the mapping pipeline -- take existing content from `main.py` and organize it in a similar fashion as done for PheKnowLator (we've had good feedback that this approach is user friendly) 

Completed notebook: **[`omop2obo_notebook`](https://www.dropbox.com/s/6p508gn2h1w7bkp/omop2obo_notebook.ipynb?dl=0)**

**Comment by callahantiff** [comment]
add Zenodo links for preprocessed ontology data to notebook for those who want to replicate our process

**Comment by callahantiff** [comment]
Done!
